version: '1'

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  adminer:
      image: adminer:4
      restart: always
      ports:
        - 8080:8080
  web2py:
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_started