"""initial with on update and delete cascade

Revision ID: 2035cd9b86c5
Revises: 
Create Date: 2024-03-16 17:56:04.323113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2035cd9b86c5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classrooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('grade', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('students_subjects',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], onupdate='cascade', ondelete='cascade'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], onupdate='cascade', ondelete='cascade'),
    sa.PrimaryKeyConstraint('student_id', 'subject_id')
    )
    op.create_table('subjects_classrooms',
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('classroom_id', sa.Integer(), nullable=False),
    sa.Column('start_h', sa.String(), nullable=True),
    sa.Column('end_h', sa.String(), nullable=True),
    sa.Column('day_of_week', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], onupdate='cascade', ondelete='cascade'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], onupdate='cascade', ondelete='cascade'),
    sa.PrimaryKeyConstraint('subject_id', 'classroom_id'),
    sa.UniqueConstraint('classroom_id', 'start_h', 'end_h', 'day_of_week')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subjects_classrooms')
    op.drop_table('students_subjects')
    op.drop_table('subjects')
    op.drop_table('students')
    op.drop_table('classrooms')
    # ### end Alembic commands ###
