"""Initial migration

Revision ID: 428d5a5ed653
Revises: 
Create Date: 2024-03-13 15:24:48.669442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '428d5a5ed653'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classrooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('grade', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('students_subjects',
    sa.Column('studentId', sa.Integer(), nullable=False),
    sa.Column('subjectId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['studentId'], ['students.id'], ),
    sa.ForeignKeyConstraint(['subjectId'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('studentId', 'subjectId')
    )
    op.create_table('subjects_classrooms',
    sa.Column('subjectId', sa.Integer(), nullable=False),
    sa.Column('classroomId', sa.Integer(), nullable=False),
    sa.Column('start', sa.String(), nullable=True),
    sa.Column('end', sa.String(), nullable=True),
    sa.Column('day', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['classroomId'], ['classrooms.id'], ),
    sa.ForeignKeyConstraint(['subjectId'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('subjectId', 'classroomId'),
    sa.UniqueConstraint('classroomId', 'start', 'end', 'day')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subjects_classrooms')
    op.drop_table('students_subjects')
    op.drop_table('subjects')
    op.drop_table('students')
    op.drop_table('classrooms')
    # ### end Alembic commands ###
