"""init conf

Revision ID: 7706aaece919
Revises:
Create Date: 2024-03-20 14:59:37.601420

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from web2py.applications.school.modules.utils.utils import (
  create_auth_tables,
  insert_mocked_data,
)


# revision identifiers, used by Alembic.
revision: str = "7706aaece919"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
  create_auth_tables()
  # ### commands auto generated by Alembic - please adjust! ###
  op.create_table(
    "classrooms",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("name", sa.String(), nullable=False),
    sa.PrimaryKeyConstraint("id"),
  )
  op.create_table(
    "students",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("name", sa.String(), nullable=False),
    sa.Column("grade", sa.String(), nullable=False),
    sa.Column("age", sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint("id"),
  )
  op.create_table(
    "subjects",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("name", sa.String(), nullable=False),
    sa.Column("grade", sa.String(), nullable=False),
    sa.PrimaryKeyConstraint("id"),
  )
  op.create_table(
    "assistances",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("student_id", sa.Integer(), nullable=True),
    sa.Column("subject_id", sa.Integer(), nullable=True),
    sa.Column("classroom_id", sa.Integer(), nullable=True),
    sa.Column("week_number", sa.Integer(), nullable=False),
    sa.Column("day_of_week", sa.String(), nullable=False),
    sa.Column("assists", sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(
      ["classroom_id"], ["classrooms.id"], onupdate="cascade", ondelete="cascade"
    ),
    sa.ForeignKeyConstraint(
      ["student_id"], ["students.id"], onupdate="cascade", ondelete="cascade"
    ),
    sa.ForeignKeyConstraint(
      ["subject_id"], ["subjects.id"], onupdate="cascade", ondelete="cascade"
    ),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint(
      "student_id", "subject_id", "classroom_id", "week_number", "day_of_week"
    ),
  )
  op.create_table(
    "schedules",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("subject_id", sa.Integer(), nullable=True),
    sa.Column("classroom_id", sa.Integer(), nullable=True),
    sa.Column("start_h", sa.String(), nullable=True),
    sa.Column("end_h", sa.String(), nullable=True),
    sa.Column("day_of_week", sa.String(), nullable=True),
    sa.ForeignKeyConstraint(
      ["classroom_id"], ["classrooms.id"], onupdate="cascade", ondelete="cascade"
    ),
    sa.ForeignKeyConstraint(
      ["subject_id"], ["subjects.id"], onupdate="cascade", ondelete="cascade"
    ),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("classroom_id", "start_h", "end_h", "day_of_week"),
  )
  insert_mocked_data()
  # ### end Alembic commands ###


def downgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_table("schedules")
  op.drop_table("assistances")
  op.drop_table("subjects")
  op.drop_table("students")
  op.drop_table("classrooms")
  # ### end Alembic commands ###
